- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
  become: true
  
- name: start nginx
  service:
      name: nginx
      state: started
  become: true

- name: Copy rc-local cfg file
  template:
    src: "../files/nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    follow: yes 
  become: true

- name: checkng nginx config
  shell:  nginx -t -c /etc/nginx/nginx.conf
  become: true

- name: checkng nginx cfg file
  shell:  cat /etc/nginx/nginx.conf
  become: true  

- name: restart nginx
  service:
      name: nginx
      state: restarted
  become: true